package com.bearya.mobile.inno.status

enum class SocketStatus {
    SOCKET_CONNECTION_AIDL,
    SOCKET_CONNECTION_SUCCESS,
    SOCKET_CONNECTION_FAIL,
    SOCKET_CONNECTION_DISCONNECT,
    SOCKET_SEND_COMPLETED_WAIT_RESPONSE,
    SOCKET_SEND_SUCCESS,
    SOCKET_SEND_FAIL,
    SOCKET_SEND_COMPLETED,
    SOCKET_SEND_START
}